# Generated by Django 3.2 on 2021-04-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('genre', models.CharField(default='', max_length=100)),
                ('publisher', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=100000)),
                ('final_rating', models.DecimalField(decimal_places=1, default='0', max_digits=2)),
                ('available', models.CharField(default='yes', max_length=100)),
                ('waiting_no', models.IntegerField(default='0')),
                ('rating_count', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('hostel', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(default='student', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default='0', max_digits=2)),
                ('idate', models.DateField()),
                ('edate', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinfo')),
            ],
        ),
    ]
