# Generated by Django 3.2 on 2021-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.CharField(choices=[('yes', 'Available'), ('no', 'In waiting'), ('hold', 'Currently in hold')], default='yes', max_length=100),
        ),
    ]
