# Generated by Django 3.2 on 2021-04-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('l', 'Librarian')], default='student', max_length=100),
        ),
    ]
