# Generated by Django 3.2 on 2021-04-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='waiting_no',
            field=models.IntegerField(default=0),
        ),
    ]
